blank_issues_enabled: false
contact_links:
  - name: ❔ Ask a question
    url: https://dirtcraft.net/discord
    about: We use Discord to provide assistance. Come and talk to use there in case of questions, comments or if you need help.